### ISSUE TITLE
Void Map permanent upgrade description

### ISSUE THREAD

**Issue by Leosirth** [Trimps/bug-tracker#157]
The Void Map permanent upgrade state:

> Upgrade your Void Map harvesting devices with the power of Bone! Each upgrade will cause 1 out of 100 Void Maps you find to be duplicated, guaranteed. 

This doesn't describe clearly the bonus each level give.

Based on the statement seems like at lvl 10 we will get 10 duplicate maps any 100 drops while I think in reality we get 1 duplicate map every 10 drops.

Could be changed to something like:

> Upgrade your Void Map harvesting devices with the power of Bone! Causing 1 out of 100 Void Maps you find to be duplicated, guaranteed.
Each level decreases the required maps drop by 10 for the duplicate to be guaranteed.

**Comment by Trimps** [comment]
Each level doesn't really decrease the required maps drop by 10! I honestly think the way it's currently worded is the most accurate way to say it. 

Level 1 causes 1/100 to be duplicated. Level 2 causes 2/100, or 1/50 to be duplicated (decreasing by 10 would be 1/90). Level 3 is 3/100, or 1/33 rather than 1/80. At level 10, you get 10/100 which is 1/10!
