### ISSUE TITLE
Standardize achievement time format

### ISSUE THREAD

**Issue by blackdiamand** [Trimps/bug-tracker#84]
**Describe the bug**
Currently we have 
"Clear Prison in less than 8 hours 0 minute 0 second from start of run"
and
"Clear Prison in less than 2:30:00 from start of run"
which are in different time formats. Pick a format and be consistent please

(also, just noticed that it should be "Clear **The** Prison in less than 2:30:00 from start of run")

**Comment by blackdiamand** [comment]
AT adds the minutes/seconds. Vanilla example: 
"Clear Prison in less than 8 hours from start of run"
vs 
"Clear Prison in less than 2:30 from start of run"

**Comment by Trimps** [comment]
This was a deliberate choice due to space constraints on the tooltip, and felt like the lesser of all the evils. "Clear The Prison in less than 2 hours and 30 minutes from start of run" is just too long for the achievement box, but having all of the times be "Clear the Prison in less than 8:00" or "Clear Spire V in less than 00:20" felt too weird. So I opted to use x hours or x minutes when I could, and xx:yy when needed.
